import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { PROD_API_URL, metalLabelMap } from "../utils/constants";
import { formatMoney, sortMetals } from "../utils/helpers";
import { cachedFetch } from "../lib/apiCache";
import dayjs from "dayjs";

export default function Summary() {
  const [summary, setSummary] = useState(null);
  const [prices, setPrices] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      cachedFetch(`${PROD_API_URL}/daily-summary`),
      cachedFetch(`${PROD_API_URL}/get-latest-price`),
    ])
      .then(([summaryData, priceData]) => {
        if (summaryData?.summary) setSummary(summaryData);
        if (priceData?.metals) {
          setPrices(
            sortMetals(priceData.metals.filter((m) => !["BTC", "ETH", "HG"].includes(m.metal_name)))
          );
        }
      })
      .finally(() => setLoading(false));
  }, []);

  const renderSummary = (text) => {
    if (!text) return null;
    return text.split("\n").map((line, i) => {
      if (!line.trim()) return <br key={i} />;
      const formatted = line
        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
        .replace(/\*(.*?)\*/g, "<em>$1</em>");
      return <p key={i} dangerouslySetInnerHTML={{ __html: formatted }} />;
    });
  };

  return (
    <div className="al-page al-summary-page">
      <div className="al-page__header">
        <h1 className="al-page__title">AI Market Summary</h1>
        <p className="al-page__subtitle">
          Daily AI-powered analysis of precious metal markets — generated by Gemini
        </p>
      </div>

      {loading ? (
        <div className="al-loading-container">
          <div className="al-loading-orb" />
          <p>Loading summary...</p>
        </div>
      ) : (
        <div className="al-summary__layout">
          {/* Main Summary */}
          <div className="al-summary__main">
            <div className="al-summary__card">
              <div className="al-summary__header">
                <span className="al-summary__badge">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                  AI Summary
                </span>
                {summary?.date && (
                  <span className="al-summary__date">
                    {dayjs(summary.date).format("DD MMM YYYY")}
                  </span>
                )}
              </div>
              <div className="al-summary__content">
                {summary?.summary ? (
                  renderSummary(summary.summary)
                ) : (
                  <div className="al-summary__empty">
                    <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                    <h3>No summary available yet</h3>
                    <p>Market summaries are generated daily after prices are fetched. Check back after 9:00 AM IST.</p>
                  </div>
                )}
              </div>
            </div>

            <div className="al-summary__info-bar">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
              <span>This summary is AI-generated using Gemini and pre-computed price data. Verify with official sources.</span>
            </div>
          </div>

          {/* Sidebar */}
          <div className="al-summary__sidebar">
            {/* Price snapshot */}
            <div className="al-summary__prices-card">
              <h3 className="al-summary__prices-title">Today's Prices</h3>
              <div className="al-summary__prices-list">
                {prices.map((m) => (
                  <div key={m.metal_name} className="al-summary__price-row">
                    <span className="al-summary__price-name">
                      {metalLabelMap[m.metal_name] || m.metal_name}
                    </span>
                    <span className="al-summary__price-val">
                      {m.price_1g ? formatMoney(m.price_1g) : "—"}
                      <span className="al-summary__price-unit">/g</span>
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Quick links */}
            <div className="al-summary__links-card">
              <h3 className="al-summary__links-title">Quick Links</h3>
              <Link to="/news" className="al-summary__link">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
                Market News
              </Link>
              <Link to="/market" className="al-summary__link">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>
                Market Dashboard
              </Link>
              <Link to="/compare" className="al-summary__link">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
                Compare Metals
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
